### ISSUE TITLE
Concussion animation breaks after firing and not moving, then firing again

### ISSUE THREAD

**Issue by videoP** [taysta/TaystJK#68] opened 2023-12-30 09:19 UTC
Reproduce

1) Fire concussion rifle in first person, observe slight weapon animation
2) Don't move
3) Fire again, observe no weapon animation

**Comment by Alereon** [comment] 2023-12-31 10:01
I am unable to reproduce this, using the master branch as of this [commit
](https://github.com/taysta/TaystJK/commit/136ead02a1e2e6811b96d74b15fa1d8675ecdbe3)

Steps i tried to reproduce the issue:

1. devmap mp/ffa1
2. /give all
3. switched to first person
4. switched to concussion rifle
5. fired a shot, and observed weapon animation
6. don't move
7. fire a shot again, observed weapon animation again

**Comment by taysta** [comment] 2024-01-21 12:13
Believe this is fixed now, and this issue was specific to tribes only.

**Closed as completed by taysta** 2024-01-21 12:13 UTC
